name = "taxis-web"
compatibility_date = "2025-01-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload.format = "directory"
upload.dir = ".next"

[[routes]]
match = "/*"
run = { type = "function", function = "_worker.js" }
